# Generated by Django 2.1 on 2020-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_poster', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_Starring', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_point', models.FloatField(default='未评分')),
                ('movie_address', models.CharField(max_length=50)),
            ],
        ),
    ]
